### ISSUE TITLE
Build with node 15

### ISSUE THREAD

**Issue by jtpio** [jupyter-rtc/jupyterlab#37]
At the moment building with Node.js 15 from a fresh copy of the repo throws the following error:

```bash
Error: Cannot find module 'buffer/package.json'
Require stack:
- /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js
- /home/user/git/jupyterlab-rtc/buildutils/lib/ensure-repo.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at requirePackage (/home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:305:16)
    at /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:281:31
    at Array.forEach (<anonymous>)
    at /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:272:27
    at Array.forEach (<anonymous>)
    at Object.getPackageGraph (/home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:268:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/git/jupyterlab-rtc/buildutils/lib/utils.js',
    '/home/user/git/jupyterlab-rtc/buildutils/lib/ensure-repo.js'
  ]
}
```

Node 14 seems to still be treating it as a warning though:

```bash
$ node scripts/ensure-buildutils.js && node buildutils/lib/ensure-repo.js
(node:237698) UnhandledPromiseRejectionWarning: Error: Cannot find module 'buffer/package.json'
Require stack:
- /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js
- /home/user/git/jupyterlab-rtc/buildutils/lib/ensure-repo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at requirePackage (/home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:305:16)
    at /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:281:31
    at Array.forEach (<anonymous>)
    at /home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:272:27
    at Array.forEach (<anonymous>)
    at Object.getPackageGraph (/home/user/git/jupyterlab-rtc/buildutils/lib/utils.js:268:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:237698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:237698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jtpio** [comment]
This is also related to #38.

**Comment by jtpio** [comment]
Closing, as this now builds and runs fine with node 15 locally in a fresh new environment with the latest rebase.
